### ISSUE TITLE
roei1wan

### ISSUE THREAD

**Issue by roei1wan** [yehonadav/learn_git#6]

**Comment by roei1wan** [comment]
im ready for review!

**Comment by yehonadav** [comment]
good job! but you forgot to close the issue

**Comment by roei1wan** [comment]
i want to add another python program that uses the requests module to crawl html data.

**Comment by ycoms1** [comment]
my file structure
git_learn
roei1wan folder
URL folder containing:
README.md
and
url.py

This small programs will ask u for the name of the site you want to 
make a HTML web page -----> dont forget to inter the full url
Example: http://www.mako.co.il

**Comment by ycoms1** [comment]
I finished writing the software

**Comment by roei1wan** [comment]
I finished writing the software
